# Generated by Django 5.0.6 on 2024-06-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocations',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='restaurantlocations',
            name='name',
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.restaurant'),
        ),
        migrations.DeleteModel(
            name='UniCampus',
        ),
        migrations.DeleteModel(
            name='RestaurantLocations',
        ),
    ]
