# Generated by Django 5.0.6 on 2024-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_remove_restaurantlocations_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='additionalInfo',
            field=models.TextField(blank=True),
        ),
    ]
