# Generated by Django 5.0.6 on 2024-06-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_order_timestamp'),
        ('testapp', '0008_order_deliveredby_order_orderedby'),
    ]

    operations = [
    ]
