# Generated by Django 5.0.6 on 2024-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_merge_20240611_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
