# Generated by Django 5.0.6 on 2024-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_alter_user_identification_alter_user_legalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
